=== PabloCCanizares/Simcan2Cloud/simulations/newscripts/jobs_schema.json
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "type": "array",
  "minItems": 1,
  "items": {
    "type": "object",
    "properties": {
      "action": {
        "type": "string",
        "enum": [
          "simulate",
          "process",
          "plot",
          "omit"
        ]
      },
      "max_coords": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "integer",
          "minimum": 1
        }
      },
      "labels": {
        "type": "string"
      },
      "config_name": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      },
      "cluster" : {
        "type": "string"
      },
      "simulations_path":{
        "type": "string"
      },
      "graphs":{
        "type": "string"
      },
      "simulation_type":{
        "type" : "string" 
      },

      "graphs_plot":{
        "type" : "string" 
      }
      
    },
    
    "required": [ 
      "action",
      "max_coords",
      "config_name",
      "cluster",
      "simulations_path"
    ]
  }
}

=== PabloCCanizares/Simcan2Cloud/simulations/newscripts/simulations.json
[
  {
    "action": "simulate",
    "max_coords": [1,1],
    "labels": "[['40000MIPS', '50000MIPS', '60000MIPS', '70000MIPS'],[128, 256, 512, 1024]]",
    "config_name": [ "test_w1s10h_cyclic_10_45_testf"],
    "cluster": "cirrus",
    "simulations_path": "../ScenarioTest",
    "simulation_type": "{'#___t#':['base']}",
    "graphs": "[ { 'name':'cpuUsage2d', 'extensions':['png'] } , { 'name':'cpuTime2d', 'extensions':['png'] } ]"
    
  }
]
